# Generated by Django 4.2.14 on 2024-08-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncientifica',
            name='departamento_evento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='area_concentracion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='doi_link_publicacion',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produccionacademica',
            name='linea_pesquisa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
