# Generated by Django 4.2.14 on 2024-08-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteDeCurva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=300)),
                ('grupo', models.CharField(max_length=2)),
                ('calendario', models.DateField()),
                ('metodologia', models.TextField()),
                ('conclusiones', models.TextField()),
                ('descripcion_grafica', models.TextField()),
                ('descripcion_tabla', models.TextField()),
                ('resultados', models.TextField()),
                ('programa', models.CharField(max_length=50)),
                ('mensurando_1', models.FloatField()),
                ('error_1', models.FloatField()),
                ('mensurando_2', models.FloatField()),
                ('error_2', models.FloatField()),
                ('chicuadrado_1', models.FloatField()),
                ('mensurando_teo', models.FloatField()),
                ('error_teo', models.FloatField()),
                ('nota_pendiente', models.CharField(max_length=5)),
                ('nota_chisquare', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DatosExperimentale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('ngrafjpg', models.CharField(max_length=50)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('x5', models.FloatField()),
                ('x6', models.FloatField()),
                ('x7', models.FloatField()),
                ('x8', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('y3', models.FloatField()),
                ('y4', models.FloatField()),
                ('y5', models.FloatField()),
                ('y6', models.FloatField()),
                ('y7', models.FloatField()),
                ('y8', models.FloatField()),
                ('dx1', models.FloatField()),
                ('dx2', models.FloatField()),
                ('dx3', models.FloatField()),
                ('dx4', models.FloatField()),
                ('dx5', models.FloatField()),
                ('dx6', models.FloatField()),
                ('dx7', models.FloatField()),
                ('dx8', models.FloatField()),
                ('dy1', models.FloatField()),
                ('dy2', models.FloatField()),
                ('dy3', models.FloatField()),
                ('dy4', models.FloatField()),
                ('dy5', models.FloatField()),
                ('dy6', models.FloatField()),
                ('dy7', models.FloatField()),
                ('dy8', models.FloatField()),
                ('nombre_grafico', models.CharField(max_length=15)),
                ('titulo_grafico', models.CharField(max_length=50)),
                ('eje_x', models.CharField(max_length=20)),
                ('eje_y', models.CharField(max_length=20)),
                ('pendiente', models.FloatField()),
                ('intercepto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ErroresEnMedicione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=2)),
                ('calendario', models.DateField()),
                ('metodologia', models.TextField()),
                ('conclusiones', models.TextField()),
                ('programa', models.CharField(max_length=50)),
                ('mensurando_1', models.FloatField()),
                ('error_1', models.FloatField()),
                ('mensurando_2', models.FloatField()),
                ('error_2', models.FloatField()),
                ('chicuadrado_1', models.FloatField()),
                ('mensurando_teo', models.FloatField()),
                ('error_teo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.FileField(upload_to='files/ajuste_de_curvas')),
            ],
        ),
    ]
